### ISSUE TITLE
SCR_CNTL_BASE variable

### ISSUE THREAD

**Issue by gongotar** [LLNL/scr#108] opened 2017-12-01 15:07 UTC
Hi,
I have installed scr 1.2.0 and I'm willing to add a `XOR` descriptor in **scr.conf** as discussed in the user manual. For now I want to have a single `XOR` descriptor in `/tmp/username/cache`. So I have added following lines to the scr.conf as described in the manual:

```
SCR_COPY_TYPE=FILE
STORE=/tmp/username/cache          GROUP=NODE   COUNT=1
CKPT=0 INTERVAL=1 GROUP=NODE   STORE=/tmp/username/cache TYPE=XOR     SET_SIZE=8
```

after running my scr test program I get following error:

> SCR v1.2.0 ABORT: rank 0 on \<NodeName\>: Failed to create store descriptor for control directory [**/tmp**] @ \<SCR_DIRECTORY\>/src/scr_storedesc.c:355

which I believe indicates that there is a default store descriptor (`/tmp`) which cannot be found among available descriptors (in this case the only available descriptor is `/tmp/username/cache` according to the _scr.conf_ file). 
I have traced the code and found out that the default store descriptor is stored in a global variable `scr_cntl_base` and its value will be set in `scr.c:841` from _scr.conf_ or _environment_ if found, and else it will be set in `scr.c:843` from a constant named `SCR_CNTL_BASE` (default descriptor `/tmp`).
This means if I want to change the value of `scr_cntl_base` I should set the correct descriptor in the _scr.conf_ or _environment_ as follows:

in scr.conf:
`SCR_CNTL_BASE = /tmp/username/cache`

or in the environment:
`export SCR_CNTL_BASE=/tmp/username/cache`

But after setting the `SCR_CNTL_BASE` value using _scr.conf_ or _environment_ and running the test program I get following error:

> SCR v1.2.0 ERROR: rank 0 on \<NodeName\>: SCR_CNTL_BASE cannot be set in the environment or user configuration file, ignoring setting

This prevents me from updating the value of `scr_cntl_base`. I'm confused about how to add my descriptor to the scr.conf file. Am I missing something?

**Comment by adammoody** [comment] 2017-12-20 20:03
Sorry for the slow reply on this.  The current behavior is at best misleading.  We'll work to improve this in a future release.  As it stands, the control directory is locked down to be set as either a compile time constant or through the system configuration file.  The system configuration file defaults to /etc/scr.conf.  Having said that, let me test things to verify whether that works.

**Comment by adammoody** [comment] 2017-12-20 20:53
Well, there is also a bug between the documentation and the code, unfortunately.

You should be able to get to to this work by specifying the control base path you want to use as a cmake option to compile in a default other than /tmp.

cmake -DSCR_CNTL_BASE=/tmp/username/cache ...

Then there is a bug in that the user guide says you should use the STORE key in a CKPT descriptor while the code actually looks for BASE.  As a work around, change STORE-->BASE in your CKPT line:

SCR_COPY_TYPE=FILE
STORE=/tmp/username/cache          GROUP=NODE   COUNT=1
CKPT=0 INTERVAL=1 GROUP=NODE   BASE=/tmp/username/cache TYPE=XOR     SET_SIZE=8

Ultimately, we'll want to change the code to use STORE, but this should work for now.

Please let me know if that helps.

**Comment by adammoody** [comment] 2017-12-22 22:51
Pushed a commit to master to look for STORE key name as documented in user guide: https://github.com/LLNL/scr/commit/f48f457c3038968c46b8f45cfbf4467b8bcdac83

**Comment by gongotar** [comment] 2017-12-28 13:01
I have tested the most recent scr (after the commit) and I still get the same error:

> SCR v1.2.0 ABORT: rank 0 on <NodeName>: Failed to create store descriptor for control directory [/tmp] @ <SCR_DIRECTORY>/src/scr_storedesc.c:355

Is there something else I should do? My scr.conf file is as follows:
```
SCR_COPY_TYPE=FILE
STORE=/tmp/username/cache          GROUP=NODE   COUNT=1
CKPT=0 INTERVAL=1 GROUP=NODE   STORE=/tmp/username/cache TYPE=XOR     SET_SIZE=8
```

I have also tried to replace STORE key with BASE (which I believe is not the case anymore), and I get following error:

> SCR v1.2.0 ERROR: rank 0 on <NodeName>: Missing one or more files for dataset 1 @ <SCR_DIRECTORY>/src/scr_flush.c:528

**Comment by adammoody** [comment] 2017-12-28 19:18
This config file should place the CACHE directory at /tmp/username/cache.  However, it requires a cmake option to move the control directory.  I think it should work if you rerun your cmake step with the following option and rebuild SCR:

cmake -DSCR_CNTL_BASE=/tmp/username/cache ...

**Comment by gongotar** [comment] 2018-02-01 14:57
Hi, sorry for the late answer, I have installed SCR with the given option `cmake -DSCR_CNTL_BASE=/tmp/username/cache` and I get the same error as before. Nothing is changed.

**Comment by gongotar** [comment] 2018-05-07 16:12
Any news on this? I noticed that running SCR with the default store `/tmp` gives the same error too. 
I install SCR as instructed by the documentation but running `make test` results in following output:

> The following tests FAILED:
	  1 - serial_test_api_start (Failed)
	  2 - serial_test_api_restart (Failed)
	  4 - parallel_test_api_start (Failed)
	  5 - parallel_test_api_restart (Failed)
	  7 - serial_test_api_multiple_start (Failed)
	  8 - serial_test_api_multiple_restart (Failed)
	 10 - parallel_test_api_multiple_start (Failed)
	 11 - parallel_test_api_multiple_restart (Failed)
	 13 - serial_test_interpose_start (Failed)
	 14 - serial_test_interpose_restart (Failed)
	 16 - parallel_test_interpose_start (Failed)
	 17 - parallel_test_interpose_restart (Failed)
	 19 - serial_test_interpose_multiple_start (Failed)
	 20 - serial_test_interpose_multiple_restart (Failed)
	 22 - parallel_test_interpose_multiple_start (Failed)
	 23 - parallel_test_interpose_multiple_restart (Failed)
	 25 - serial_test_ckpt_C_start (Failed)
	 26 - serial_test_ckpt_C_restart (Failed)
	 28 - parallel_test_ckpt_C_start (Failed)
	 29 - parallel_test_ckpt_C_restart (Failed)
	 31 - serial_test_ckpt_F_start (Failed)
	 32 - serial_test_ckpt_F_restart (Failed)
	 34 - parallel_test_ckpt_F_start (Failed)
	 35 - parallel_test_ckpt_F_restart (Failed)
Errors while running CTest

However I can call SCR functions in my code without getting library errors. Then I have a sample code just as the example of the tutorial. `scr.conf` contains following default lines:
```CNTLDIR=/tmp BYTES=1GB
SCR_CNTL_BASE=/tmp
CACHEDIR=/tmp BYTES=12GB
SCR_CACHE_BASE=/tmp

SCR_DB_ENABLE=0

SCR_DB_HOST=host45
SCR_DB_USER=scr_insert
SCR_DB_PASS=12345
SCR_DB_NAME=scr

STORE=/tmp GROUP=NODE COUNT=2
```


The slurm script has a line pointing to the `scr.conf`:
`export SCR_CONF_FILE=<path to scr conf>/scr.conf`

Everything seems to be correct as instructed by the tutorial. But I get still the same error as before.

**Comment by adammoody** [comment] 2018-05-08 00:46
I see you refer to two different errors above.  When you say the same error, do you mean you're currently seeing the "Failed to create store descriptor for control directory" or the "Missing one or more files for dataset 1" error?

The second error is further along than the first, meaning it created the control directory store descriptor and the directory itself.

**Comment by adammoody** [comment] 2018-05-08 17:49
Ah, ok.  So it looks like valid is not set here when calling SCR_Complete_checkpoint().  You'll want to set this value to be 1 if the process wrote its file successfully, or 0 otherwise.  That flag indicates to SCR that the checkpoint file was written without errors.  Since it's not set explicitly, it's likely assuming the "random" value of 0, which SCR_Complete_checkpoint takes to mean that the process failed in writing its file.  Try setting valid=1 and see if that helps.

**Comment by gongotar** [comment] 2018-05-09 14:19
Oh, now it's working, thanks.
But I have noticed a huge bandwidth degradation in case of mpi job running on more than one node. for my case the checkpoint size is 2 GB and I run following function for checkpointing: 

```
  double start_cp0 = MPI_Wtime();
  SCR_Start_checkpoint();
  sprintf(checkpoint_file, "%s/rank_%d.ckpt", checkpoint_dir, rank);
  char scr_file[SCR_MAX_FILENAME];
  SCR_Route_file(checkpoint_file, scr_file);
  double start_cp1 = MPI_Wtime();
  FILE* fs = fopen(scr_file, "w");
  int valid = 0;
  if (fs != NULL) {
    int rc = fwrite(buf, 1, (size_t)sizet, fs);
    if (rc >0){
      valid = 1;
    }
    fclose(fs);
  }
  double end_cp1 = MPI_Wtime();
  double delta1 = end_cp1 - start_cp1;
  printf("rank %d inner bandwidth: %7.2f\n", rank, sizet/(delta1*GB_UNIT));
  SCR_Complete_checkpoint(valid);
  double end_cp0 = MPI_Wtime();
  double delta0 = end_cp0 - start_cp0;
  printf("rank %d outer bandwidth: %7.2f\n", rank, sizet/(delta0*GB_UNIT));
```

The printed output of the code is as follows:

> rank 0 inner bandwidth:    2.10
rank 1 inner bandwidth:    2.10
rank 0 outer bandwidth:    0.16
rank 1 outer bandwidth:    0.16

Changing the size of the checkpoint doesn't change much the outer/inner bandwidth values. In my scr.conf file I haven't used any schemes (xor, partner, ...). The only used scheme is the node's local storage. And I have set `export SCR_FLUSH=-1` in the slurm wrapper script. 
This is not however the case if the job uses only one node. In this case the inner and outer bandwidth have similar values. Do you know why I experience such performance degradation in case of multiple nodes?

**Comment by adammoody** [comment] 2018-05-09 17:28
Ok, good.  We're making progress.

To disable the flush, you'll want to set SCR_FLUSH=0 instead of -1.  I would expect this setting to affect both the single node and two-node runs, though.  I recommend this change, but I don't know that it will help your performance here.

SCR uses XOR encoding by default if there is more than one node, but it falls back to SINGLE if the job is using a single node.  When going from one compute node to two, there will be some additional overhead for the XOR encoding vs SINGLE.  With XOR, SCR must read the entire checkpoint file and compute and store redundancy data.  The amount of redundancy data depends on the XOR set size, which in this case would be just two since you have two nodes.  The major costs involved are:

SINGLE: write file
PARTNER: write file, read file back, network transfer of file, write file again (partner copy)
XOR: write file, read file back, XOR computation + network transfer of file, write redundancy data (where data size = file size when using 2 nodes)

Assuming the XOR computation and network costs are below the I/O costs, then you could expect XOR bandwidth might be 33% of the SINGLE bandwidth.

Do you see any difference with two ranks/two nodes vs XOR using PARTNER?

If so, that would suggest the XOR compute is slow.  If not, then perhaps the network is slowing things down.

How does performance change with XOR when using 3 ranks on 3 nodes, and 4 ranks on 4 nodes?

Increasing the node count reduces the size of the redundancy data.

**Comment by gongotar** [comment] 2018-05-11 14:01
Thanks for the explanation. I tested the job (checkpoint size of 2 GB) with more nodes and the performance got better (though not very much):

> nodes = 2: checkpoint duration = 17s
nodes =16: checkpoint duration = 13s

knowing that both read and write bandwidth are almost 2 GB/s (1s write, 1s read, 1/(n-1)s XOR segment write) I assume for two nodes _network+XOR computation_ takes 14s and for 16 nodes it takes almost 11s. 
Now I assume there are two possible scenarios of how XOR is computed:
1. Each rank computes only its own XOR-parity-segment of size 2/(n-1)GB by receiving 1/(n-1) portion of checkpoints of each rank and computing locally the XOR data and then writes the segment locally. 
2. All ranks send their checkpoints the a single rank (possibly rank 0), the whole XOR computation 
is done in this single rank and then the parity segments of size 1/(n-1) are partitioned and distributed among all ranks.

In the first scenario the duration of network transferring of checkpoint-portion (size 1/(n-1)) changes according to the XOR set size (which I assume is the number of nodes). Also the XOR computation duration depends on the set size. I assume in this scenario we should have seen way better performance for 16 nodes (almost 3s or 4s).
In the second scenario the checkpoint is transferred completely and also the XOR computation is done for the whole checkpoints. So the duration here is not a variable of the XOR set size. The only variable part in this case is segment transfer/write duration.
If I'm getting it correctly by comparing the cases of 2 nodes (14s) and 16 nodes (11s) I assume the second scenario is used in SCR which justifies the results I get. Am I correct in this?

I have also tested Partner by adding following line to the scr.conf file:
```
CKPT=0 INTERVAL=1 STORE=/tmp GROUP=NODE COUNT=1
CKPT=1 INTERVAL=2 STORE=/tmp GROUP=NODE COUNT=1 TYPE=PARTNER
```
The observed durations are almost the same as XOR and I don't see duration changes every 2 checkpoints (interval=2). This is confusing, am I doing it correctly?
And something else, can I ever disable the default XOR scheme for more than one node?

**Comment by gongotar** [comment] 2018-05-14 11:38
I tested the XOR scheme for 1 and 2 tasks per node. However testing more tasks per node will be complicated because of slurm max memory limit determined by the administrator. The results of XOR tests is also as follows:
> 2 nodes, 1 task per node: duration 17s
2 nodes, 2 tasks per node: duration 32s
16 nodes, 1 task per node: duration 13s
16 nodes, 2 tasks per node: duration 22s

Then I tested the **Partner** scheme as well by setting `SCR_COPY_TYPE=PARTNER` (only using Partner). The performance was as follows:

> 2 nodes, 1 task per node: duration 20s
2 nodes, 2 tasks per node: duration 35s
16 nodes, 1 task per node: duration 17s
16 nodes, 2 tasks per node: duration 30s

However I tested the speed of transmitting 2 GBs of checkpoints manually by `MPI_Send` and `MPI_Recv`. The whole data was transferred to the other node in 1.8s which is far shorter than the extra overhead I experience in case of partner scheme. This does not match the following estimation:

> PARTNER duration = write file + read file back + network transfer of file + write file again
= 1s + 1s + 1.8s + 1s = 4.8s

And here I believe we don't have computations as in XOR scheme. 

Do you have an idea why the Partner scheme (and possibly XOR) delivers such performance degradation?

**Comment by adammoody** [comment] 2018-05-21 18:57
Yes, this shows a big jump going from 1 process per node to 2 procs/node.  We also have some internal timers in SCR that could shed some light.  You should get some timings for applying the redundancy schemes with the following:

SCR_DEBUG=1

Can you run with that and let me know what it shows?

**Comment by adammoody** [comment] 2018-05-23 00:41
Hmm, something strange is going on, but the problem is still not clear.  Adding a second rank per node nearly doubles your cost, suggesting that something is slow and is effectively serializing the work.

For comparison, here are results I see writing with SINGLE to ramdisk, PARTNER to ramdisk, and PARTNER to an SSD:
```
SCR_DEBUG=1
SCR_COPY_TYPE=FILE
STORE=/tmp   GROUP=NODE   COUNT=1
STORE=/l/ssd GROUP=NODE   COUNT=1
CKPT=0 INTERVAL=1 GROUP=NODE   STORE=/tmp   TYPE=SINGLE
CKPT=1 INTERVAL=2 GROUP=NODE   STORE=/tmp   TYPE=PARTNER
CKPT=2 INTERVAL=3 GROUP=NODE   STORE=/l/ssd TYPE=PARTNER
```

```
srun -n2 -N2 ./test_api -s 1GB
Init: Min 0.011031 s    Max 0.011060 s  Avg 0.011045 s
No checkpoint to restart from
At least one rank (perhaps all) did not find its checkpoint
SCR v1.2.0: rank 0 on catalyst322: Starting dataset ckpt.1
SCR v1.2.0: rank 0 on catalyst322: scr_reddesc_apply: 0.000039 secs, 2.147484e+09 bytes, 52698985.595092 MB/s, 26349492.797546 MB/s per proc
Completed checkpoint 1.
SCR v1.2.0: rank 0 on catalyst322: Deleting dataset 1 from cache
SCR v1.2.0: rank 0 on catalyst322: Starting dataset ckpt.2
SCR v1.2.0: rank 0 on catalyst322: scr_reddesc_apply: 1.380486 secs, 2.147484e+09 bytes, 1483.535250 MB/s, 741.767625 MB/s per proc
Completed checkpoint 2.
SCR v1.2.0: rank 0 on catalyst322: Starting dataset ckpt.3
SCR v1.2.0: rank 0 on catalyst322: scr_reddesc_apply: 2.556553 secs, 2.147484e+09 bytes, 801.078681 MB/s, 400.539340 MB/s per proc
Completed checkpoint 3.
```

Then when I run 2 ranks per node, the PARTNER cost to ramdisk is about the same at 1.4 secs, and the PARTNER cost to SSD increases from 2.5 to 3.5 seconds.
```
srun -n4 -N2 ./test_api -s 1GB
Init: Min 0.013269 s    Max 0.013282 s  Avg 0.013274 s
No checkpoint to restart from
At least one rank (perhaps all) did not find its checkpoint
SCR v1.2.0: rank 0 on catalyst322: Starting dataset ckpt.1
SCR v1.2.0: rank 0 on catalyst322: scr_reddesc_apply: 0.000060 secs, 4.294967e+09 bytes, 68719477.280000 MB/s, 17179869.320000 MB/s per proc
Completed checkpoint 1.
SCR v1.2.0: rank 0 on catalyst322: Deleting dataset 1 from cache
SCR v1.2.0: rank 0 on catalyst322: Starting dataset ckpt.2
SCR v1.2.0: rank 0 on catalyst322: scr_reddesc_apply: 1.401434 secs, 4.294967e+09 bytes, 2922.719729 MB/s, 730.679932 MB/s per proc
Completed checkpoint 2.
SCR v1.2.0: rank 0 on catalyst322: Starting dataset ckpt.3
SCR v1.2.0: rank 0 on catalyst322: scr_reddesc_apply: 3.538541 secs, 4.294967e+09 bytes, 1157.539129 MB/s, 289.384782 MB/s per proc
Completed checkpoint 3.
```

By default, SCR operates on file chunks of 128KB.  We can try different sizes here to see whether that helps in either accessing your storage or sending via the network.  What do you see with the following:

```
SCR_MPI_BUF_SIZE=1MB
or
SCR_MPI_BUF_SIZE=8MB
```

**Comment by adammoody** [comment] 2018-05-24 21:31
There is a higher debug level of SCR_DEBUG=2.  I don't think that will provide much more info in this case.

It would be a useful test to run using ramdisk, e.g., set your cache to use /dev/shm.  That should provide very high disk bandwidth.  If the slowdown is still there, that would point more to the network.  If it goes away, that would point more to the storage.

You could also try some tests in which you comment out portions of the swap_file code.  For example, you could comment out the write(), read(), or send/recv calls in the while loop of this function:

https://github.com/LLNL/scr/blob/e00fdd85dd18fd7061759a699931d60477a80982/src/scr_cache_rebuild.c#L163

This is the routine that partner copy uses to copy a file from one node to another.  Commenting these lines out would lead to incorrect code, but it could help in isolating the cause of the slowdown.

**Comment by gongotar** [comment] 2018-06-18 09:36
Sorry for the late answer on this! I changed the scr.conf file to use ` /dev/shm` as follows:
```
SCR_COPY_TYPE=FILE
CKPT=0 INTERVAL=1 GROUP=NODE   STORE=/dev/shm TYPE=SINGLE
```

This gives me following warnings and causes the job to be killed:

> SCR v1.2.0 WARNING: rank 1 on cumu01-01: Failed to find store descriptor named /dev/shm @ <SCR_DIRECTORY>/src/scr_reddesc.c:504
> SCR v1.2.0 WARNING: rank 0 on cumu01-00: Failed to find store descriptor named /dev/shm @ <SCR_DIRECTORY>/src/scr_reddesc.c:504
> srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
> srun: error: cumu01-00: task 0: Exited with exit code 255
> srun: error: cumu01-01: task 1: Killed

Though `/dev/shm` path in available on every node. Is there something I should do so SCR is able to find the store descriptor?

**Comment by gongotar** [comment] 2018-06-19 15:18
I found the bottleneck. It is in fact the `scr_close` calls right after the while loop. It takes all the extra time not included in the estimations. The lengthy operation in `scr_close` is the `fsync` call. It is also the case for XOR scheme. It appears that for SINGLE scheme no fsync is called. 
I should investigate the problem of `fsync` to know why it takes so long.

**Comment by adammoody** [comment] 2018-06-19 20:00
You could probably also create a STORE=/dev/shm entry in your configuration file as another way to clear up those store descriptor errors.

It's good to see that ramdisk provides better behavior.  We generally recommend storing checkpoint data in ramdisk if you can.  Not all applications have enough spare memory to do that, but if you can, it's very fast.

Nice work in tracking down fsync as the underlying problem.  Let me know if you find a way to improve that.  I don't have ideas off hand, but it has to do with the OS and file system flushing data from memory to disk.

To gain some performance, you could consider dropping the fsync call and rebuilding SCR without it.  However, for correctness, it is functionally important to keep the fsync.

SCR uses this fsync to be sure the data is on disk before it considered the dataset to be "complete".  If you drop the call to fsync, and the job were to be killed before the OS / file system has really written the data to disk, then SCR will think the dataset is valid when it is really not.  If you're not too worried about that, you could drop the fsync and just be on the lookout for this failure case occurring.

**Comment by adammoody** [comment] 2021-06-04 22:53
FYI, very recent updates have resolved the cause for the original reason this ticket was opened.

1) It is now possible to set SCR_CNTL_BASE at runtime through an environment variable, whereas that previously was not possible.
2) SCR will now create the default store descriptor, even when there is no explicit entry for it in the config file.

I'll go ahead and close this issue, since it's been a while.  Feel free to reopen if needed.

**Closed by adammoody** 2021-06-04 22:53 UTC
