### ISSUE TITLE
Can we add an API call to SCR that sets user parameters?

### ISSUE THREAD

**Issue by mmpozulp** [LLNL/scr#91] opened 2017-09-27 17:12 UTC
Section 6 "Configure a job" of the SCR User's Manual says 

> SCR searches the following locations in the following order for a parameter value, taking the first value it finds.
>
> 1. Environment variables,
> 2. User configuration file,
> 3. System configuration file,
> 4. Compile-time constants.
>
> Some parameters, such as the location of the control directory, cannot be specified by the user. Such parameters must be either set in the system configuration file or hard-coded into SCR as compile-time constants.

Can we add an API call to SCR that sets user parameters, like those specified in 1. and 2.? Doing this would allow users of my code to put all scr configuration parameters inside of the input deck to my code.

Note that if SCR needs user-settable parameters at SCR_Init time, then they could be passed there instead of a new API call.

**Comment by becker33** [comment] 2017-09-27 17:37
Closing as duplicate of #40. #40 has been tagged for v1.3 and assigned to me. By noting #40 by reference here, this conversation will be linked to from #40.

**Closed by becker33** 2017-09-27 17:37 UTC
